use_frameworks!

target 'PodDemo_Example' do
  pod 'PodDemo', :path => '../'

  target 'PodDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
